### ISSUE TITLE
Could we have a master?

### ISSUE THREAD

**Issue by fsedarkalex** [openhab/openhab-syno-spk#14] opened 2016-03-16 06:51 UTC
Hi again :)

I would love to see a package for 2.0.0-SNAPSHOT (instead of only the beta 2).
I don't know if it's possible to implement an update button - probably in form of an uninstall-script that lets you choose between uninstalling and updating?
##

**Comment by cniweb** [comment] 2016-03-17 20:40
Hi @fsedarkalex,

Currently the package only supports a clean installation.
An update is not planned! This must necessarily be carried out by the console from, because there is no alteration to the installation on the DiskStation, only the used JAR libraries need to be updated.

Since 2.0 is currently only beta!
An update of the SNAPSHOTS could e.g. carried out by a cron job that the JARs invites nightly of Bintray down.

Once 2.0 is stable, there will be a corresponding package.

Thank you for your involvement!

Chris

**Comment by yphyph01** [comment] 2016-12-23 10:26
Hi @fsedarkalex 
If that could help, please see this post:
https://community.openhab.org/t/how-to-update-oh2-on-synology/17503/5
Regards

**Comment by cniweb** [comment] 2017-01-13 13:39
Close - Duplicate of #42

**Closed by cniweb** 2017-01-13 13:39 UTC
Labels: enhancement
