### ISSUE TITLE
openhab user not created

### ISSUE THREAD

**Issue by SparkoUK** [openhab/openhab-syno-spk#59] opened 2017-03-02 15:53 UTC
Installing OpenHAB-2.1.0.002-SNAPSHOT-DSM6-syno-noarch-0.001.spk on a DS214Play no user openhab was created on install.  Although the package claims to be running it has permission issues.

**Comment by shagkie** [comment] 2017-03-02 16:01
I have more or less the same problem installing it on a DS415+.  The service said it's running but I can't seem to connect to it via web interface.

**Comment by SparkoUK** [comment] 2017-03-02 16:36
I wonder if the postinst function is running in the install as it seems to be setting up most of the things that  seem not to have actually happened.

**Comment by jhlweb** [comment] 2017-03-09 19:20
See post ["https://community.openhab.org/t/synology-diskstation/1446/178 ](https://community.openhab.org/t/synology-diskstation/1446/178 )
there is a problem with downloading the zip file inside of the script.

**Comment by cniweb** [comment] 2017-03-14 19:35
@SparkoUK can you try my new version:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.004-SNAPSHOT-DSM6

**Comment by shagkie** [comment] 2017-03-15 21:54
This new "2.1.0.004" snapshot didn't seem to make a difference on my ds415+

**Comment by cniweb** [comment] 2017-03-16 21:15
OK, I think the problem is the download from cloudbes build result.
The older versions are on bintray and it works...

**Comment by cniweb** [comment] 2017-07-27 21:30
@SparkoUK and @jhlweb 
Can we close this issue?

**Comment by SparkoUK** [comment] 2017-07-28 07:51
Yes

**Closed** 2017-07-28 09:45 UTC
